# Generated by Django 4.2.13 on 2024-06-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="package",
            name="total_bookings",
            field=models.IntegerField(default=0),
        ),
    ]
