# Generated by Django 4.2.13 on 2024-06-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0002_package_duration_package_total_bookings"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
