# Generated by Django 4.2.13 on 2024-06-22 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
        ("packages", "0003_package_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="hotels",
        ),
        migrations.AddField(
            model_name="package",
            name="hotels",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="hotels.hotel",
            ),
        ),
    ]
