# Generated by Django 4.2.13 on 2024-06-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0004_remove_package_hotels_package_hotels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="status",
        ),
    ]
